"""Configuration package for vsep."""

from config.variables import (
    # Repository URLs
    UVR_PUBLIC_REPO_URL,
    UVR_VIP_REPO_URL,
    AUDIO_SEPARATOR_REPO_URL,
    UVR_MODEL_DATA_URL_PREFIX,
    UVR_VR_MODEL_DATA_URL,
    UVR_MDX_MODEL_DATA_URL,
    # Paths
    MDXC_YAML_PATH_PREFIX,
    # Download config
    MAX_DOWNLOAD_WORKERS,
    DOWNLOAD_CHUNK_SIZE,
    DOWNLOAD_TIMEOUT,
    HTTP_POOL_CONNECTIONS,
    HTTP_POOL_MAXSIZE,
    # Model data files
    VR_MODEL_DATA_FILENAME,
    MDX_MODEL_DATA_FILENAME,
    # Helper functions
    get_repo_url,
    get_mdx_yaml_url,
    get_fallback_url,
    # Logging
    DEFAULT_LOG_LEVEL,
    DEFAULT_LOG_FORMAT,
    # Separator defaults
    DEFAULT_MODEL_FILE_DIR,
    DEFAULT_OUTPUT_FORMAT,
    DEFAULT_SAMPLE_RATE,
    DEFAULT_NORMALIZATION_THRESHOLD,
    DEFAULT_AMPLIFICATION_THRESHOLD,
    DEFAULT_OUTPUT_SINGLE_STEM,
    DEFAULT_INVERT_USING_SPEC,
    DEFAULT_USE_SOUNDFILE,
    DEFAULT_USE_AUTOCAST,
    DEFAULT_USE_DIRECTML,
    DEFAULT_CHUNK_DURATION,
    # Ensemble
    VALID_ENSEMBLE_ALGORITHMS,
    DEFAULT_ENSEMBLE_ALGORITHM,
    # Stem mapping
    STEM_NAME_MAP,
    # Architecture default params
    DEFAULT_MDX_PARAMS,
    DEFAULT_VR_PARAMS,
    DEFAULT_DEMUCS_PARAMS,
    DEFAULT_MDXC_PARAMS,
)

__all__ = [
    # Repository URLs
    "UVR_PUBLIC_REPO_URL",
    "UVR_VIP_REPO_URL",
    "AUDIO_SEPARATOR_REPO_URL",
    "UVR_MODEL_DATA_URL_PREFIX",
    "UVR_VR_MODEL_DATA_URL",
    "UVR_MDX_MODEL_DATA_URL",
    # Paths
    "MDXC_YAML_PATH_PREFIX",
    # Download config
    "MAX_DOWNLOAD_WORKERS",
    "DOWNLOAD_CHUNK_SIZE",
    "DOWNLOAD_TIMEOUT",
    "HTTP_POOL_CONNECTIONS",
    "HTTP_POOL_MAXSIZE",
    # Model data files
    "VR_MODEL_DATA_FILENAME",
    "MDX_MODEL_DATA_FILENAME",
    # Helper functions
    "get_repo_url",
    "get_mdx_yaml_url",
    "get_fallback_url",
    # Logging
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_LOG_FORMAT",
    # Separator defaults
    "DEFAULT_MODEL_FILE_DIR",
    "DEFAULT_OUTPUT_FORMAT",
    "DEFAULT_SAMPLE_RATE",
    "DEFAULT_NORMALIZATION_THRESHOLD",
    "DEFAULT_AMPLIFICATION_THRESHOLD",
    "DEFAULT_OUTPUT_SINGLE_STEM",
    "DEFAULT_INVERT_USING_SPEC",
    "DEFAULT_USE_SOUNDFILE",
    "DEFAULT_USE_AUTOCAST",
    "DEFAULT_USE_DIRECTML",
    "DEFAULT_CHUNK_DURATION",
    # Ensemble
    "VALID_ENSEMBLE_ALGORITHMS",
    "DEFAULT_ENSEMBLE_ALGORITHM",
    # Stem mapping
    "STEM_NAME_MAP",
    # Architecture default params
    "DEFAULT_MDX_PARAMS",
    "DEFAULT_VR_PARAMS",
    "DEFAULT_DEMUCS_PARAMS",
    "DEFAULT_MDXC_PARAMS",
]
